packages:
  - 'web/*'

catalog:
  '@samatech/postcss-basics': 0.7.4
  '@samatech/vue-store': 0.7.1
  'date-fns': 4.1.0
  'jwt-decode': 4.0.0
  postcss: 8.5.3
  vue: 3.5.13
  vue-router: 4.5.0
  vite: 6.2.2
  typescript: 5.8.2
  '@floating-ui/vue': 1.1.6
  '@samatech/fetch-api': 0.12.1
  '@types/node': 22.13.10
  '@vitejs/plugin-vue': 5.2.2
  terser: 5.39.0
